### ISSUE TITLE
how do you initialize the tracker? I have problems when I run main.py as shown below.

### ISSUE THREAD

**Issue by bosunrunner** [kcg2015/Vehicle-Detection-and-Tracking#33]
Traceback (most recent call last):
  File "E:/PycharmProject/Vehicle-Detection-and-Tracking/main.py", line 201, in <module>
    image_box = pipeline(image)
  File "E:/PycharmProject/Vehicle-Detection-and-Tracking/main.py", line 115, in pipeline
    = assign_detections_to_trackers(x_box, z_box, iou_thrd=0.3)
  File "E:/PycharmProject/Vehicle-Detection-and-Tracking/main.py", line 71, in assign_detections_to_trackers
    if IOU_mat[m[0], m[1]] < iou_thrd:
IndexError: index 0 is out of bounds for axis 0 with size 0
matched_idx:(array([], dtype=int32), array([], dtype=int64))，shape:(2, 0)
matched_idx:(array([], dtype=int32), array([], dtype=int64))，shape:(2, 0)

#########################
Can you tell me how to solve it? Thank you?

**Comment by ntquyen11** [comment]
I have the same problem and I don't know why having it
